### ISSUE TITLE
creacion de clases dao e interfaces

### ISSUE THREAD

**Issue by marcioRLopez** [marcioRLopez/2019#1]
necesito que crees las clases dao y las interfases  para las clases Usuario y User

**Comment by Jose8922** [comment]
Marcio necesito que crees el index

**Comment by marcioRLopez** [comment]
problemas con el push del index
indicador de problema "failed push"

**Comment by Jose8922** [comment]
Lo vemos más tarde, a descansar. Buenas Noches
