### ISSUE TITLE
Base de Datos

### ISSUE THREAD

**Issue by Jose8922** [marcioRLopez/2019#10]
Intentaré crear la base de Datos y el Mapeo

**Comment by Jose8922** [comment]
Error en el Mapeo al ejecutar "TestCreateUsuario" guiandome con el video del profe

**Comment by marcioRLopez** [comment]
intento de seguir los mismos pasos, mejor esperar clase de lunes 10/6 para consulta de errores.

**Comment by marcioRLopez** [comment]
por ahora exito 0% en mapeo
