### ISSUE TITLE
fusion de clases

### ISSUE THREAD

**Issue by marcioRLopez** [marcioRLopez/2019#11]
fusionar clases User y DuenioMascota por indicar los mismo ( son el DUEÑO O PROPIETARIO  de la Mascota).
es decir verificar sus atributos y unir en una sola clase, que estos sean mas completos, pues Clase DuenioMascota tiene atributos insuficientes para su identificacion, combinar con los atributos de User mas completos
a su vez verificar que estos cambios no influya o impliquen error en las clases correspondientes a estas Ej. Dao, DaoImp, Beans, Formbeans

@ezequielreneclavijo 
@Jose8922 
@marcioRLopez 
@AnaBruno2

**Comment by ezequielreneclavijo** [comment]
Tuve que cambiar el nombre de la clase user por propietariodemascota. Además la clase propietariodemascota hereda atributos de clase persona.

**Comment by ezequielreneclavijo** [comment]
Tengan en cuanta que las librerías primefaces7.0 y la bluesky se borran. Agréguenla en sus neetbeans si es que les da error.

**Comment by ezequielreneclavijo** [comment]
Voy a empezar a conectar el login con el beans

**Comment by Jose8922** [comment]
Reunion para seguir planificando mejor las clases con un diagrama de clases...que opianan uds?

**Comment by Jose8922** [comment]
Así vamos cerrando bien las ideas del proyecto!

**Comment by ezequielreneclavijo** [comment]
OK, Mañana horario de clases.

**Comment by ezequielreneclavijo** [comment]
Me salta un error cuando hago el commit.

**Comment by ezequielreneclavijo** [comment]
Y cuando hago el push también error me da

**Comment by ezequielreneclavijo** [comment]
Me muestra éste mensaje de error: El repositorio remoto contiene confirmaciones no fusionadas en la rama local. Abra la salida para ver más información.

**Comment by ezequielreneclavijo** [comment]
En el managedBean login tenemos que escribir el método de validación de usuario y su contraseña. Hay que pedir ayudita al profe

**Comment by AnaBruno2** [comment]
Clases fusionadas....
