### ISSUE TITLE
CONTINUAR CON INTENTO DE CONEXION Y CREACION DE BASE DE DATOS

### ISSUE THREAD

**Issue by marcioRLopez** [marcioRLopez/2019#12]
Continuar con conexion y creacion de base de datos, insistir en esto, porque no se puede avanzar en el proyecto. proponer alternativas y busqueda de material (youtube, google)
@ezequielreneclavijo 
@Jose8922
 @marcioRLopez
@AnaBruno2

**Comment by Jose8922** [comment]
Continuando viendo la base de datos...intentare conectar la base de datos!

**Comment by Jose8922** [comment]
Por lo pronto nos centremos ahora con la base de datos para manejar mejor las clases y hacer el mapeo.

**Comment by ezequielreneclavijo** [comment]
En el managedBean login tenemos que escribir el método de validación de usuario y su contraseña. Hay que pedir ayudita al profe

**Comment by marcioRLopez** [comment]
por ahora 0% de exito en conexion de base de datos..... varios errores...

**Comment by ezequielreneclavijo** [comment]
Voy a crear una base de datos con lista

**Comment by ezequielreneclavijo** [comment]
Ya se puede trabajar con la BD SQL Workbench, ahora pasaremos a realizar el ABM.
