### ISSUE TITLE
Revisión de Código

### ISSUE THREAD

**Issue by AnaBruno2** [marcioRLopez/2019#13]
@ezequielreneclavijo y @Jose8922 
 
Problemas con las clases UsuarioFormsBean y UsuarioBean. Revisarla ya que estan tirando error por cambios en la clase Doctor, eliminacion del atributo propietarioDeMascota.
Esta comentado la porcion de codigo que tira error.

**Comment by Jose8922** [comment]
Lo veré a la brevedad

**Comment by AnaBruno2** [comment]
terminado
