### ISSUE TITLE
creacion de vista

### ISSUE THREAD

**Issue by Jose8922** [marcioRLopez/2019#15]
Por favor necesito que crees la vista del proyecto @ezequielreneclavijo

**Comment by ezequielreneclavijo** [comment]
@Jose8922  @AnaBruno2  @marcioRLopez Creado las vistas propietarios, usuarioDoctor, pacientes y atenciones. Faltaría algunos detalles de tablas en donde se muestren los datos y enlazarlo con base de datos y managedbeans. Y funcionalidad (métodos) en donde corresponda.

**Comment by ezequielreneclavijo** [comment]
@Jose8922 @marcioRLopez @AnaBruno2  he creado dos formularios (tablas) para mostrar pacientes dar alta y modificar. Falta enlazar a los managedbean y realizar sus métodos.

**Comment by ezequielreneclavijo** [comment]
Como no pude hacer conexión con BD SQL he creado un listado de usuarios para prueba, lo que se va a probar es la funcionalidad de logeo de usuario Doctor.
