### ISSUE TITLE
MIRAR LAS CLASES DEL DOMINIO

### ISSUE THREAD

**Issue by AnaBruno2** [marcioRLopez/2019#16]
@ezequielreneclavijo 
@Jose8922 
@marcioRLopez

PROBLEMAS EN LAS CLASES DEL DOMINIO!!!!!
HAY QUE MODIFICAR LA MAYORIA TOMANDO EN CUENTA SUS RELACIONES ENTRE TABLAS. ES MUY PRIORITARIO ESTO..

**Comment by AnaBruno2** [comment]
DE OTRA FORMA CUALQUIER MAPEO QUE SE REALIZE NO FUNCIONARA COMO DEBE SER

**Comment by ezequielreneclavijo** [comment]
Ya está revisado. Borre el atributo tipo de la clase vacuna.

**Comment by ezequielreneclavijo** [comment]
Hice de nuevo el mapeo de la clase doctor. Corregí el error que me dijiste.

**Comment by ezequielreneclavijo** [comment]
@AnaBruno2 @Jose8922 @marcioRLopez estoy en proceso de realización de los mapeos. Esa parte dejenmelo a mi para que no haya problemas al hacer los pull commit push.

**Comment by AnaBruno2** [comment]
ok

**Comment by AnaBruno2** [comment]
voy armando los daos

**Comment by ezequielreneclavijo** [comment]
@AnaBruno2 @marcioRLopez @Jose8922 agregue el hibernate.cfg.xml e HibernateUtil

**Comment by ezequielreneclavijo** [comment]
@marcioRLopez @AnaBruno2 @Jose8922 puse un archivo de base de datos para hacer la prueba de logueo. Pero tiene una sola tabla usuarios. Hagan la conexión y prueben que si funca. Estoy generando las otras tablas.

**Comment by ezequielreneclavijo** [comment]
@Jose8922 @marcioRLopez @AnaBruno2 me faltan generar las dos tablas que pertenecen a las clases Atencion y Mascota, estas clases tienen como atributo objetos. Estoy en proceso de generar esas dos que faltan, hasta ahora no me sale.

**Comment by marcioRLopez** [comment]
.......
