### ISSUE TITLE
Continuar avanzando

### ISSUE THREAD

**Issue by ezequielreneclavijo** [marcioRLopez/2019#5]
Marcio pasa nuevas tareas.

**Comment by AnaBruno2** [comment]
Reunión hoy jueves... Definir horario!!!  @Jose8922  @ezequielreneclavijo  @marcioRLopez

**Comment by Jose8922** [comment]
Reunion 17:00hs Biblioteca FI. @ezequielreneclavijo @AnaBruno2 @marcioRLopez

**Comment by marcioRLopez** [comment]
reunion lograda biblioteca facultad de ingenieria hrs 17:00  a 19.00 asistentes @ezequielreneclavijo ,
@AnaBruno2 , 
@Jose8922 
@marcioRLopez 

puntos aclarados designacion de nuevas tareas,
