### ISSUE TITLE
Generación interfaz login

### ISSUE THREAD

**Issue by ezequielreneclavijo** [marcioRLopez/2019#6]
Necesito que crees la interfaz visual (jsf Page) de login.

**Comment by marcioRLopez** [comment]
agregue index.xhtml, tuve un pequeño inconveniente en el commit, pues olvide comentar todo lo que subia, lo agrego aca
"agrego index.xhtml la interfaz visual del login...

**Comment by Jose8922** [comment]
Por favor ERROR en la clase "User" @AnaBruno2 verificar sino eliminar la clase

**Comment by AnaBruno2** [comment]
@jose8922 en primera instancia era necesario la clase luego la decisión grupal por cambios en el proyecto se eliminar causando error en el proyecto y finalmente es necesaria dicha clase así que fue añadida nuevamente.
