### ISSUE TITLE
completar datos usuario github

### ISSUE THREAD

**Issue by marcioRLopez** [marcioRLopez/2019#9]
favor terminar el ingreso de datos de usuario de github de cada uno ej. foto identificatoria , campo de nombre y apellido y empresa 
todo esto para una mayor identificacion por el profe....
@ezequielreneclavijo 
@Jose8922 
@AnaBruno2

**Comment by Jose8922** [comment]
ok en proceso...

**Comment by Jose8922** [comment]
Perfil Actualizado

**Comment by ezequielreneclavijo** [comment]
Ya lo actualicé, pero no se muestra en la sección Insights

**Comment by ezequielreneclavijo** [comment]
Agregué imagen.
